version: "3.9"

services:
  postgres_dev:
    image: postgres:18-alpine
    container_name: postgres_dev_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres@123
      POSTGRES_DB: DEVBYTES
    ports:
      - "6432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - community-network

  postgres_test:
    image: postgres:18-alpine
    container_name: postgres_test_container
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - community-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres_dev
      - postgres_test
    networks:
      - community-network
    extra_hosts:
      - "localhost:127.0.0.1"

volumes:
  postgres_dev_data:
  postgres_test_data:

networks:
  community-network:
    driver: bridge
