version: "3.9"

services:
  postgres_container:
    image: postgres:18-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_container_data:/var/lib/postgresql/data
    networks:
      - community-network

  redis:
    image: redis:7-alpine
    container_name: redis_container
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - community-network

  minio:
    image: minio/minio:latest
    container_name: minio_container
    ports:
      - "${MINIO_UI_PORT}:9000"
      - "${MINIO_ADMIN_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - community-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres_container
    networks:
      - community-network
    extra_hosts:
      - "localhost:127.0.0.1"

volumes:
  postgres_container_data:
  minio_data:

networks:
  community-network:
    driver: bridge
